#!/usr/bin/env bun

import {
  cloudBaseDomain,
  localBaseDomain,
  localDevPorts,
  productSlug,
} from '@repro/env/topology'

/**
 * regenerate infra/nginx/local.conf and infra/hosts.example from product.ts knobs.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')

function write(relativePath: string, content: string): void {
  writeFileSync(join(root, relativePath), content, 'utf8')
  console.log(`wrote ${relativePath}`)
}

function nginxServerBlock(serverName: string, upstreamPort: number): string {
  return `
# --- ${serverName} (:${upstreamPort}) ---
server {
    listen 443 ssl;
    server_name ${serverName};

    ssl_certificate     /etc/ssl/certs/${localBaseDomain}.pem;
    ssl_certificate_key /etc/ssl/private/${localBaseDomain}-key.pem;

    location / {
        proxy_pass http://127.0.0.1:${upstreamPort};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
`
}

function nginxRedirectBlock(serverName: string, targetHost: string): string {
  return `
# --- ${serverName} → ${targetHost} ---
server {
    listen 443 ssl;
    server_name ${serverName};

    ssl_certificate     /etc/ssl/certs/${localBaseDomain}.pem;
    ssl_certificate_key /etc/ssl/private/${localBaseDomain}-key.pem;

    return 301 https://${targetHost}$request_uri;
}
`
}

export function syncLocalInfra(): void {
  const nginxConf = `# generated by scripts/sync-local-infra.ts — do not edit; re-run sync after product.ts changes
# ${productSlug}: local ${localBaseDomain}, cloud ${cloudBaseDomain}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

proxy_connect_timeout 60s;
proxy_send_timeout    60s;
proxy_read_timeout    60s;
proxy_buffering       on;
proxy_buffer_size     16k;
proxy_buffers         8 16k;
proxy_busy_buffers_size 32k;
${nginxServerBlock(`api.${localBaseDomain}`, localDevPorts.api)}
${nginxServerBlock(`console.${localBaseDomain}`, localDevPorts.console)}
${nginxServerBlock(`docs.${localBaseDomain}`, localDevPorts.docs)}
${nginxServerBlock(localBaseDomain, localDevPorts.marketing)}
${nginxRedirectBlock(`www.${localBaseDomain}`, localBaseDomain)}

server {
    listen 80;
    server_name
        ${localBaseDomain}
        www.${localBaseDomain}
        api.${localBaseDomain}
        console.${localBaseDomain}
        docs.${localBaseDomain};
    return 301 https://$host$request_uri;
}
`

  write('infra/nginx/local.conf', nginxConf)

  write(
    'infra/hosts.example',
    `# generated — merge into /etc/hosts (and Windows hosts on WSL2)
127.0.0.1 ${localBaseDomain}
127.0.0.1 www.${localBaseDomain}
127.0.0.1 api.${localBaseDomain}
127.0.0.1 console.${localBaseDomain}
127.0.0.1 docs.${localBaseDomain}
`,
  )

  console.log(`synced ${productSlug} (${localBaseDomain} / ${cloudBaseDomain})`)
}

if (import.meta.main) {
  syncLocalInfra()
}
